apiVersion: cert-manager.io/v1alpha2
kind: ClusterIssuer
metadata:
  name: dev-letsencrypt 
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: elsavies@yovoydelivery.com
    privateKeySecretRef:
      name: letsencrypt
    solvers:
    - http01:
        ingress:
          class: nginx